apiVersion: v1
kind: Service
metadata:
  name: __imageRepository__
  namespace: __namespace__
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: __targetPort__
    targetPort: __targetPort__  
  selector:
    app: __imageRepository__
